#!/usr/bin/env python3
"""
CJK Font Generator for ESP32
Generates 1bpp bitmap font data from TTF/OTF fonts for CJK character display.
"""

import argparse
import os
import sys
from PIL import Image, ImageDraw, ImageFont


def parse_args():
    parser = argparse.ArgumentParser(description="Generate CJK font bitmap data for ESP32")
    parser.add_argument("--chars", required=True, help="Path to CJK character list file")
    parser.add_argument("--font", required=True, help="Path to TTF/OTF font file")
    parser.add_argument("--size", type=int, default=12, help="Font size in pixels (default: 12)")
    parser.add_argument("--out", required=True, help="Output header file path")
    return parser.parse_args()


def load_characters(filepath):
    """Load unique CJK characters from file, skipping comments and empty lines."""
    chars = []
    seen = set()
    
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            
            for char in line:
                if ord(char) >= 0x4E00 and char not in seen:
                    chars.append(char)
                    seen.add(char)
    
    return chars


def render_glyph(char, font, size):
    """Render a single character to a 1bpp bitmap."""
    img = Image.new('1', (size, size), 0)
    draw = ImageDraw.Draw(img)
    
    # Get character bounding box
    bbox = draw.textbbox((0, 0), char, font=font)
    if bbox is None:
        return None
    
    width = bbox[2] - bbox[0]
    height = bbox[3] - bbox[1]
    
    # Center the glyph
    x = (size - width) // 2 - bbox[0]
    y = (size - height) // 2 - bbox[1]
    
    # Draw centered character
    draw.text((x, y), char, font=font, fill=1)
    
    return img


def image_to_1bpp_bytes(img):
    """Convert image to row-major 1bpp bytes (MSB first)."""
    width, height = img.size
    bytes_per_row = (width + 7) // 8
    data = bytearray()
    
    pixels = img.load()
    for y in range(height):
        row_byte = 0
        bit_count = 0
        for x in range(width):
            if pixels[x, y]:
                row_byte |= (0x80 >> (x % 8))
            bit_count += 1
            if bit_count == 8:
                data.append(row_byte)
                row_byte = 0
                bit_count = 0
        if bit_count > 0:
            data.append(row_byte)
    
    return bytes(data)


def generate_header(chars, bitmaps, size, out_path):
    """Generate C header file with font data."""
    glyph_count = len(chars)
    bytes_per_glyph = (size * size + 7) // 8
    
    # Sort characters by codepoint for binary search
    sorted_pairs = sorted(zip(chars, bitmaps), key=lambda x: ord(x[0]))
    sorted_chars = [p[0] for p in sorted_pairs]
    sorted_bitmaps = [p[1] for p in sorted_pairs]
    
    lines = []
    lines.append("// Auto-generated CJK font data")
    lines.append("// DO NOT EDIT MANUALLY")
    lines.append("// Generated by tools/generate_cjk_font.py")
    lines.append("")
    lines.append("#ifndef FONT_CJK_DATA_H")
    lines.append("#define FONT_CJK_DATA_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include <pgmspace.h>")
    lines.append("")
    lines.append(f"#define CJK_FONT_SIZE {size}")
    lines.append(f"#define CJK_GLYPH_COUNT {glyph_count}")
    lines.append(f"#define CJK_BYTES_PER_GLYPH {bytes_per_glyph}")
    lines.append("")
    
    # Codepoint array
    lines.append("static const uint32_t CJK_CODEPOINTS[] PROGMEM = {")
    codepoint_lines = []
    for i in range(0, glyph_count, 8):
        chunk = sorted_chars[i:i+8]
        codepoints = [f"0x{ord(c):04X}" for c in chunk]
        codepoint_lines.append("    " + ", ".join(codepoints) + ",")
    lines.append("\n".join(codepoint_lines))
    lines.append("};")
    lines.append("")
    
    # Bitmap array
    lines.append(f"static const uint8_t CJK_BITMAPS[{glyph_count}][{bytes_per_glyph}] PROGMEM = {{")
    for i, bitmap in enumerate(sorted_bitmaps):
        hex_bytes = [f"0x{b:02X}" for b in bitmap]
        lines.append("    {" + ", ".join(hex_bytes) + "}, // " + sorted_chars[i])
    lines.append("};")
    lines.append("")
    lines.append("#endif // FONT_CJK_DATA_H")
    
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))


def main():
    args = parse_args()
    
    # Load characters
    print(f"Loading characters from {args.chars}...")
    chars = load_characters(args.chars)
    print(f"Found {len(chars)} unique CJK characters")
    
    # Load font
    print(f"Loading font from {args.font}...")
    try:
        font = ImageFont.truetype(args.font, args.size)
    except Exception as e:
        print(f"Error loading font: {e}")
        sys.exit(1)
    
    # Render glyphs
    print(f"Rendering {len(chars)} glyphs at {args.size}x{args.size}...")
    bitmaps = []
    failed = []
    
    for char in chars:
        img = render_glyph(char, font, args.size)
        if img is None:
            failed.append(char)
            continue
        bitmap = image_to_1bpp_bytes(img)
        bitmaps.append(bitmap)
    
    if failed:
        print(f"Warning: Failed to render {len(failed)} characters: {''.join(failed)}")
    
    # Generate header
    print(f"Generating header file: {args.out}...")
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    generate_header(chars, bitmaps, args.size, args.out)
    
    # Report statistics
    glyph_count = len(bitmaps)
    bytes_per_glyph = (args.size * args.size + 7) // 8
    total_size = glyph_count * bytes_per_glyph + glyph_count * 4  # bitmaps + codepoints
    
    print(f"\nDone!")
    print(f"  Characters: {glyph_count}")
    print(f"  ROM size: {total_size} bytes ({total_size / 1024:.1f} KB)")
    print(f"  Output: {args.out}")


if __name__ == "__main__":
    main()
